### ISSUE TITLE
Rotation of S3?

### ISSUE THREAD

**Issue by paulackerman** [paulackerman/SmalyukhSharedCode#1]
I noticed that the preimages are tilted, kinda like when I rotate S3 before a stereographic projection. Maybe this is expected but I expected to see something symmetric for the following command:

> clear, nn = fknotansatz('a',1,'b',1,'alpha',1,'beta',1); fvisualizePreimages('phi',linspace(0,2*pi,8))

I think that alpha > beta is important however, the above command may still help visualize the issue. The bottom is fat and the top is skinny when I expected uniform thickness. 

The image produced by the command:
![image](https://user-images.githubusercontent.com/34322424/33702400-978639c2-dae0-11e7-810b-d4d5a0cd9071.png)

**Comment by paulackerman** [comment]
By switching z1 and z0, I obtain the symmetric figure that I was expecting.

**Comment by paulackerman** [comment]
maybe theta and phi are switched and there still seems to be a strange "rotation"

>clear, nn = fknotansatz('a',1,'b',1,'alpha',1,'beta',0); fvisualizePreimages('phi',pi/4,'theta',linspace(0,pi/1.5,4))

![image](https://user-images.githubusercontent.com/34322424/33702950-10ad2b06-dae3-11e7-99d5-7df0ec74955e.png)

**Comment by paulackerman** [comment]
This is what I get when I do a rotation. Notice that after some rotation the green preimages look like the first image! Can the equations that define n1,n2,n3 be altered to reflect the more symmetric orientation from the start of this gif?

![stack](https://user-images.githubusercontent.com/34322424/33704167-95988f72-dae8-11e7-872a-1af4a8b3eae7.gif)

**Comment by paulackerman** [comment]
Thanks, David! 
I understand now that 

>z1.^a./z0.^b; % for links

this is for axis symmetric links and 

>'z1.^alpha.*z0.^beta./(z1.^a+z0.^b)' % trefoil

can be used for the special case of the trefoil!
I have made this change in the code where the default is now links and the user can define other "w" functions using 'wknot' input. I will try to update comments and such once I learn about some of the other types of knots that we can try!

**Comment by dave-soliton** [comment]
I think I see your problem.
To write down an axially symmetric configuration you need something like.
W=Z1^n/Z0,  this gives a Q=n axial Hopfion.
W=(Z1^alpha * Z0^beta)/(Z1^3-Z0^2), gives a Q=2*alpha +3*beta trefoil knot Hopfion.
W=(Z1^alpha * Z0^beta)/(Z1^5-Z0^2), gives a Q=2*alpha +5*beta cinquefoil knot Hopfion.
I can keep on going with these, but these are the first few 'simplest' torus knots.
Let me know if you need more.
A good paper is https://arxiv.org/pdf/0705.1468.pdf .

**Comment by paulackerman** [comment]
@dave-soliton I used 

> z1.^a./z0.^b; % for links

Does this make sense? It makes axis symmetric a,b type links. I think this gives Q=ab

**Comment by dave-soliton** [comment]
No. For a link try,
W=(Z1^(n+1))/(Z1^2-Z0^2), this will give a Q=2n+1 Hopfion.
It will give two Q=n Hopfions which link each other.

**Comment by paulackerman** [comment]
Ahh, what I suggested must give linked preimages not linked hopfion!

**Comment by dave-soliton** [comment]
Yes. This will give a linked preimage of n=(0,0,-1).
