### ISSUE TITLE
Hayley's First Issue!

### ISSUE THREAD

**Issue by hayleysohn** [paulackerman/SmalyukhSharedCode#3]
Testing out how to add issues on github. 

> a = [1 2 3 4];

![screen shot 2017-12-07 at 6 26 36 pm](https://user-images.githubusercontent.com/34323284/33746721-2efbd5fa-db7c-11e7-9369-a7f61f028c10.png)

**Comment by hayleysohn** [comment]
Yay, it worked!

**Comment by paulackerman** [comment]
Hi Haley, nice job. Now lets do some work...
