### ISSUE TITLE
orientation of S2

### ISSUE THREAD

**Issue by paulackerman** [paulackerman/SmalyukhSharedCode#7]
Hey guys,

Here is a good one to check and fix... I have added a wiki page which includes some test code. I am not sure if the orientation of S2 points, all for phi = 0, agree with the preimage visualization! I suspect that we have S2 rotated by 180 degrees or something like that. Can you check this and report back with your preferred definitions of theta and phi? I hope to make the s2plotter consistent with fvisualizePreimages!

-Paul

**Comment by benjstai** [comment]
I guess there is something wrong in the rotation you did in the code. I had modified your code a bit for my plotter.

I replaced in your code from line 173 to line 188 with the following: 

positionNew1 = rotationMatrix2*rotationMatrix1*[xc(1,:); yc(1,:); zc(1,:)];
positionNew2 = rotationMatrix2*rotationMatrix1*[xc(2,:); yc(2,:); zc(2,:)];

xc = [positionNew1(1,:); positionNew2(1,:)];
yc = [positionNew1(2,:); positionNew2(2,:)];
zc = [positionNew1(3,:); positionNew2(3,:)];

I think this is more consistent with how rotation matrices work in general.

**Comment by benjstai** [comment]
note there should be a * between rotationMatrix2 and rotationMatrix1 and after. Somehow it was interpreted as some typesetting syntax.

**Comment by paulackerman** [comment]
I'll have a look now!

**Comment by paulackerman** [comment]
I think this looks a lot better. You are right about the rotation, now it is much easier to follow. It will be useful if you insert your code using fences >```

> "fences", which are made up of three accent grave marks (aka "tick marks")

https://github.com/radiovisual/markdown-for-everyone

ex:
```matlab
positionNew1 = rotationMatrix2*rotationMatrix1*...
               [xc(1,:); yc(1,:); zc(1,:)];
positionNew2 = rotationMatrix2*rotationMatrix1*...
               [xc(2,:); yc(2,:); zc(2,:)];

% reassemble the two sets of points into X Y Z format:
xc = [positionNew1(1,:); positionNew2(1,:)];
yc = [positionNew1(2,:); positionNew2(2,:)];
zc = [positionNew1(3,:); positionNew2(3,:)];
```

Let me know what you think and I'll close this issue if you are happy with the updates.

**Comment by benjstai** [comment]
Looks good!
